config/routes.rb
Rails.application.routes.draw do

  get 'admin/admin'

  get 'submit_question/create'

  resources :game_setups

  #admin routes
  get 'admin/admin/:page_number(/:keyword)', to:'admin#admin', as:'admin'
  get 'admin/edit_user/:id', to:'admin#edit_user', as:'admin_edit_user'
  post 'admin/update_user/:id', to:'admin#update_user', as:'admin_update_user'

  #gameplay routes
  get 'gameplay/spinner/:id', to: 'gameplay#spinner', as: 'gameplay_spinner'
  get 'gameplay/spin/:game_id', to: 'gameplay#spin', as: 'gameplay_spin'
  get 'gameplay/choose_category/:game_id', to: 'gameplay#choose_category', as:'gameplay_choose_category'
  get 'gameplay/challenge_select_pieces/:game_id', to: 'gameplay#challenge_select_pieces', as: 'challenge_select_pieces'
  get 'gameplay/challenge_setup', to: 'gameplay#challenge_setup', as: 'challenge_setup'
  get 'gameplay/challenge_next_question/:game_id/:challenge_id', to: 'gameplay#challenge_next_question', as: 'challenge_next_question'

  #question routes
  get 'question/question/:game_id/:category_id/:is_crown/:is_challenge(/:challenge_id)', to: 'question#question', as: 'question_with_params'
  get 'question/question', to: 'question#question', as: 'question'
  get 'question/answered_question/:game_id/:question_id/:answer_id/:is_crown/:is_challenge(/:challenge_id)(/:did_not_answer)', to: 'question#answered_question', as: 'answered_question'

  get 'powerup/fifty_fifty/:is_crown_or_challenge', to: 'powerup#fifty_fifty', as: 'power_up_fifty_fifty'
  get 'powerup/extend_time/:is_crown_or_challenge', to: 'powerup#extend_time', as: 'power_up_extend_time'
  get 'powerup/skip_question/:game_id/:question_id/:answer_id/:is_crown/:is_challenge(/:challenge_id)', to: 'powerup#skip_question', as: 'power_up_skip_question'

  #question_ratings routes
  get 'question_rating/show/:question_id', to: 'question_rating#show', as: 'show_question_rating'
  post 'question_rating/create', to: 'question_rating#create', as: 'question_ratings'

  #opponent search routes
  get 'search_for_opponents/select_opponent/:page_number(/:keyword)', to: 'search_for_opponents#select_opponent', as: 'select_opponent'
  get 'search_for_opponents/create_game', to: 'search_for_opponents#create_game', as: 'create_game_with_opponent'

  #home routes
  get 'home/index'
  post 'home/create_game_setup', to: 'home#create_game_setup', as: 'create_game_setup'
  get 'home/setup_new_game/:id', to: 'home#setup_new_game', as: 'setup_new_game'

  #profile routes
  get 'profile/view'

  #submit question routes
  get 'submit_question/new', to: 'submit_question#new', as: 'submit_question'
  post 'submit_question/create', to: 'submit_question#create', as: 'create_question'

  #review questions routes
  get 'question_review/review(/:page_number)', to: 'question_review#review', as: 'review_questions'
  get 'question_review/approve/:question_id/:page_number', to: 'question_review#approve', as: 'approve_question'
  get 'question_review/deny/:question_id/:page_number', to: 'question_review#deny', as: 'deny_question'

  #devise routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  get 'welcome/index'

  root to: 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/answered_question.rb
class AnsweredQuestion < ActiveRecord::Base
  belongs_to :category
  belongs_to :game_detail
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_details
  has_many :users
end

app/models/game_challenge.rb
class GameChallenge < ActiveRecord::Base
  has_many :questions, -> { uniq }, :through => :game_challenge_questions
end

app/models/game_detail.rb
class GameDetail < ActiveRecord::Base
  belongs_to :game
  has_one :user
  has_many :game_pieces, -> { uniq }, :through => :game_detail_game_pieces
  has_many :questions, -> { uniq }, :through => :game_detail_questions
  has_many :answered_questions
  has_many :game_challenges
end

app/models/game_piece.rb
class GamePiece < ActiveRecord::Base
  has_one :category
end

app/models/game_setup.rb
class GameSetup < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :answers
  has_many :game_details, :through => :game_detail_questions
end

app/models/question_rating.rb
class QuestionRating < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :game
  belongs_to :game_detail
  def self.create_from_omniauth(params)
    if(params['info'].nil? == false && params['info']['image'].nil? == false)
      image = params['info']['image']
    else
      image = asset_path + 'images/default-player-icon.png'
    end

    attributes = {
      email: params['info']['email'],
      provider: params['provider'],
      uid: params['uid'],
      password: Devise.friendly_token,
      image: image
    }

    create(attributes)
  end

  has_many :authentications, class_name: 'UserAuthentication', dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/gameplay_helper.rb
module GameplayHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/powerup_helper.rb
module PowerupHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/admin.html.erb
<div class="media">
  <div class="media-body">
    <h1 class="text-center">Admin</h1>
    <hr/>
    <div class="col-lg-12 col-sm-12">
      <%= form_tag(admin_path(0), method: :get) do %>
          <%= text_field_tag :keyword, nil, class:'field col-lg-offset-1 col-lg-7 col-sm-offset-1 col-sm-7', placeholder:'Search by Username or Email...' %>
          <!--<input type="text" class="field col-lg-offset-1 col-lg-7 col-sm-offset-1 col-sm-7" placeholder="Search by Username or Email..."/>-->
          <%= submit_tag 'Search', class:'btn btn-primary col-lg-offset-1 col-lg-2 col-sm-offset-1 col-sm-2 ' %>
      <% end %>
    </div>
    <div class="clearfix"></div>
    <hr/>
    <table class="table">
      <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= if(user.role == GlobalConstants::PLAYER)
                    'Player'
                elsif(user.role == GlobalConstants::REVIEWER)
                  'Reviewer'
                end %></td>
        <td>
          <div class="btn-toolbar">
            <%= link_to 'Edit User', admin_edit_user_path(user.id), class: 'btn btn-xs btn-success' %>
          </div>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
    <% if @total_pages > 1 %>
        <div class="text-center">
          <%= link_to 'Prev', admin_path(@current_page - 1, @keyword), class: (@current_page == 0 ? 'btn disabled' : 'btn') %>
          <% (0...@total_pages).each do |page_number| %>
              <%=  link_to_if page_number != @current_page, (page_number + 1), admin_path(page_number, @keyword), class: 'btn' do %>
                  <span class="btn"><%= page_number + 1 %></span>
              <% end %>
          <% end %>
          <%= link_to 'Next', admin_path(@current_page + 1, @keyword), class: (@current_page + 1 == @total_pages ? 'btn disabled' : 'btn') %>
          <p>Page <%= @current_page + 1 %> of <%= @total_pages %></p>
        </div>
        <div class="clearfix"></div>
    <% end %>
    <hr/>
  </div>
</div>

app/views/admin/edit_user.html.erb
<div class="media">
  <div class="media-body">
    <h1 class="text-center">Edit User</h1>
    <hr/>
    <%= form_for(@user, url: admin_update_user_path(@user.id), method: :post) do |f| %>
        <label class="col-lg-1 col-sm-1">Username</label> <p><%= @user.username %></p>
        <div class="clearfix"></div>
        <label class="col-lg-1 col-sm-1">Email</label> <p><%= @user.email %></p>
        <div class="clearfix"></div>
        <label class="col-lg-1 col-sm-1">Role</label>
        <%= select_tag(:user_role, options_from_collection_for_select(@user_roles, 'constant_id', 'name', @user.role)) %>
        <div class="clearfix"></div>
        <hr/>
        <div class="actions">
          <%= link_to "Back", admin_path(0), class:'btn btn-default' %>
          <%= f.submit "Submit", class:'btn btn-primary' %>
        </div>
    <% end %>
  <hr/>
  </div>
</div>