config/routes.rb
Rails.application.routes.draw do

  get 'admin/admin'

  get 'submit_question/create'

  resources :game_setups

  #admin routes
  get 'admin/admin/:page_number(/:keyword)', to:'admin#admin', as:'admin'
  get 'admin/edit_user/:id', to:'admin#edit_user', as:'admin_edit_user'
  post 'admin/update_user/:id', to:'admin#update_user', as:'admin_update_user'

  #gameplay routes
  get 'gameplay/spinner/:id', to: 'gameplay#spinner', as: 'gameplay_spinner'
  get 'gameplay/spin/:game_id', to: 'gameplay#spin', as: 'gameplay_spin'
  get 'gameplay/choose_category/:game_id', to: 'gameplay#choose_category', as:'gameplay_choose_category'
  get 'gameplay/challenge_select_pieces/:game_id', to: 'gameplay#challenge_select_pieces', as: 'challenge_select_pieces'
  get 'gameplay/challenge_setup', to: 'gameplay#challenge_setup', as: 'challenge_setup'
  get 'gameplay/challenge_next_question/:game_id/:challenge_id', to: 'gameplay#challenge_next_question', as: 'challenge_next_question'

  #question routes
  get 'question/question/:game_id/:category_id/:is_crown/:is_challenge(/:challenge_id)', to: 'question#question', as: 'question_with_params'
  get 'question/question', to: 'question#question', as: 'question'
  get 'question/answered_question/:game_id/:question_id/:answer_id/:is_crown/:is_challenge(/:challenge_id)(/:did_not_answer)', to: 'question#answered_question', as: 'answered_question'

  get 'powerup/fifty_fifty/:is_crown_or_challenge', to: 'powerup#fifty_fifty', as: 'power_up_fifty_fifty'
  get 'powerup/extend_time/:is_crown_or_challenge', to: 'powerup#extend_time', as: 'power_up_extend_time'
  get 'powerup/skip_question/:game_id/:question_id/:answer_id/:is_crown/:is_challenge(/:challenge_id)', to: 'powerup#skip_question', as: 'power_up_skip_question'

  #question_ratings routes
  get 'question_rating/show/:question_id', to: 'question_rating#show', as: 'show_question_rating'
  post 'question_rating/create', to: 'question_rating#create', as: 'question_ratings'

  #opponent search routes
  get 'search_for_opponents/select_opponent/:page_number(/:keyword)', to: 'search_for_opponents#select_opponent', as: 'select_opponent'
  get 'search_for_opponents/create_game', to: 'search_for_opponents#create_game', as: 'create_game_with_opponent'

  #home routes
  get 'home/index'
  post 'home/create_game_setup', to: 'home#create_game_setup', as: 'create_game_setup'
  get 'home/setup_new_game/:id', to: 'home#setup_new_game', as: 'setup_new_game'

  #profile routes
  get 'profile/view'

  #submit question routes
  get 'submit_question/new', to: 'submit_question#new', as: 'submit_question'
  post 'submit_question/create', to: 'submit_question#create', as: 'create_question'

  #review questions routes
  get 'question_review/review(/:page_number)', to: 'question_review#review', as: 'review_questions'
  get 'question_review/approve/:question_id/:page_number', to: 'question_review#approve', as: 'approve_question'
  get 'question_review/deny/:question_id/:page_number', to: 'question_review#deny', as: 'deny_question'

  #devise routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  get 'welcome/index'

  root to: 'welcome#index'

end

app/controllers/gameplay_controller.rb
class GameplayController < ApplicationController

  respond_to :html, :js

  include ApplicationHelper

  def spinner
    if(current_user && current_user.role == GlobalConstants::PLAYER)
      @game = Game.where(id: params[:id]).first
      @opponent = get_opponent(@game)
      @player_game_detail = @game.game_details.where(player_id: current_user.id).first
      @player_game_pieces = GameDetailGamePiece.where(game_detail_id: @player_game_detail.id).pluck(:game_piece_id)
      @opponent_game_detail = @game.game_details.where(player_id: @opponent.id).first
      @opponent_game_pieces = GameDetailGamePiece.where(game_detail_id: @opponent_game_detail.id).pluck(:game_piece_id)
      @game_pieces = GamePiece.all

      open_challenge = GameChallenge.where('game_id= ? AND winning_player_id IS NULL ', @game.id).first
      if(open_challenge != nil)
        flash[:notice] = open_challenge.player_id == current_user.id ? "Challenge In Progress" : "You've been challenged for a game piece"
        redirect_to challenge_next_question_path(@game.id, open_challenge.id)
      end
    else
      redirect_to welcome_index_path
    end
  end

  def spin
    @game_id = params[:game_id]
    @game = Game.where(id: @game_id).first
    @category_ids_array = Category.pluck(:id)
    if(rand(2) == 1)
      @category_ids_array.push(-1)
    end
    @random_category_id = @category_ids_array[rand(@category_ids_array.count)]
    @category_string = @random_category_id != -1 ? Category.where(id: @random_category_id).first.name : :crown
    @rotation = get_category_spinner_degrees(@category_string)
    @category_image_url = GamePiece.where(category_id: @random_category_id).first.image_url unless @random_category_id == -1
  end

  def choose_category
    if(current_user && current_user.role == GlobalConstants::PLAYER)
      @game = Game.where(id: params[:game_id]).first
      @game_detail = @game.game_details.where(player_id: current_user.id).first
      @player_game_pieces = GameDetailGamePiece.where(game_detail_id: @game_detail.id).pluck(:game_piece_id)
      @game_pieces_in_threes = GamePiece.all.each_slice(3)
    else
      redirect_to welcome_index_path
    end
  end

  def challenge_select_pieces
    if(current_user && current_user.role == GlobalConstants::PLAYER)
      @game = Game.where(id: params[:game_id]).first
      player_game_detail = @game.game_details.where(player_id: current_user.id).first
      @player_game_pieces = GameDetailGamePiece.where(game_detail_id: player_game_detail.id).pluck(:game_piece_id)
      opponent = get_opponent(@game)
      opponent_game_detail = @game.game_details.where(player_id: opponent.id).first
      opponent_game_pieces = GameDetailGamePiece.where(game_detail_id: opponent_game_detail.id).pluck(:game_piece_id)
      @game_pieces = GamePiece.all
      @eligible_game_pieces = opponent_game_pieces - @player_game_pieces
    else
      redirect_to welcome_index_path
    end

  end

  # TODO: Have challenge serve up the same questions to each player
  def challenge_setup
    opponent_game_piece_id = params[:opponent_category_id]
    wager_game_piece_id = params[:wager_category_id]

    game = Game.where(id: params[:game_id]).first
    player_game_detail = game.game_details.where(player_id: current_user.id).first
    opponent = get_opponent(game)
    opponent_game_detail = game.game_details.where(player_id: opponent.id).first

    challenge = GameChallenge.new
    challenge.game_id= game.id

    challenge.player_detail_id= player_game_detail.id
    challenge.player_id = current_user.id
    challenge.opponent_detail_id= opponent_game_detail.id
    challenge.opponent_id= opponent.id

    challenge.opponent_game_piece_id= opponent_game_piece_id
    challenge.wager_game_piece_id= wager_game_piece_id

    if(challenge.save)
      category_ids_array = Category.pluck(:id)
      random_category_id = category_ids_array[rand(category_ids_array.count)]
      redirect_to question_with_params_path(game.id, random_category_id, :false, :true, challenge.id)
    end
  end

  def challenge_next_question
    game = Game.where(id: params[:game_id]).first
    challenge = GameChallenge.where(id: params[:challenge_id]).first

    category_ids_array = Category.pluck(:id)
    random_category_id = category_ids_array[rand(category_ids_array.count)]

    if(challenge != nil)
      if(current_user.id == challenge.player_id)
        if(challenge.player_correct_count + challenge.player_incorrect_count < 6)
          redirect_to question_with_params_path(game.id, random_category_id, :false, :true, challenge.id)
        else
          game.player_turn = get_opponent(game).id
          if(game.save)
            flash[:notice] = "Your opponent will now partake in the challenge"
            redirect_to home_index_path
          end
        end
      elsif(current_user.id == challenge.opponent_id)
        if(challenge.opponent_correct_count + challenge.opponent_incorrect_count < 6)
          redirect_to question_with_params_path(game.id, random_category_id, :false, :true, challenge.id)
        elsif(challenge.opponent_correct_count == challenge.player_correct_count)
          flash[:notice] = 'Tie Breaker'
          redirect_to question_with_params_path(game.id, random_category_id, :false, :true, challenge.id)
        else
          if(challenge.player_correct_count > challenge.opponent_correct_count)
            opponent_game_piece = GameDetailGamePiece.where('game_detail_id=? AND game_piece_id=?', challenge.opponent_detail_id, challenge.opponent_game_piece_id).first
            if(opponent_game_piece != nil)
              opponent_game_piece.destroy
            end
            GameDetailGamePiece.create(game_detail_id: challenge.player_detail_id, game_piece_id: challenge.opponent_game_piece_id)
            challenge.winning_player_id= challenge.player_id
          else
            wager_game_piece = GameDetailGamePiece.where('game_detail_id=? AND game_piece_id=?', challenge.player_detail_id, challenge.wager_game_piece_id).first
            if(wager_game_piece != nil)
              wager_game_piece.destroy
            end
            challenge.winning_player_id= challenge.opponent_id
          end
          winning_player = User.where(id: challenge.winning_player_id).first
          if(winning_player.nil? == false)
            winning_player.xp += GlobalConstants::CHALLENGE_WON_XP_VALUE unless winning_player.nil? == true
            handle_player_leveling
            winning_player.currency += GlobalConstants::CHALLENGE_WON_CURRENCY_VALUE
            winning_player.save
          end
          game.player_turn = get_opponent(game).id
          if(game.save && challenge.save)
            redirect_to home_index_path
          end
        end
      end
    end
  end

  private

  ART_DEG = 2690
  ENTERTAINMENT_DEG = 3000
  GEOGRAPHY_DEG = 2900
  HISTORY_DEG = 2430
  SCIENCE_DEG = 2845
  SPORTS_DEG = 2740
  CROWN_DEG = 2946

  def get_category_spinner_degrees(category_string)
    case category_string
      when :art.to_s
        return ART_DEG
      when :entertainment.to_s
        return ENTERTAINMENT_DEG
      when :geography.to_s
        return GEOGRAPHY_DEG
      when :history.to_s
        return HISTORY_DEG
      when :science.to_s
        return SCIENCE_DEG
      when :sports.to_s
        return SPORTS_DEG
      when :crown.to_s
        return CROWN_DEG
      else
        return CROWN_DEG
    end
  end

  def challenge_available(player_game_pieces, opponent_game_pieces)
    opponent_game_pieces.count > 0 && player_game_pieces.count > 0 && (opponent_game_pieces - player_game_pieces).count > 0
  end

  helper_method :get_opponent, :challenge_available

end

app/helpers/gameplay_helper.rb
module GameplayHelper
end

app/views/gameplay/challenge_select_pieces.html.erb
<div class="text-center">
  <h2>Choose the Character You Want</h2>
</div>
<hr/>
<div class="media-body">
  <%= form_tag(challenge_setup_path, method: :get, multipart: true) do %>
      <%= hidden_field_tag :game_id, @game.id %>
          <div class="row">
            <div>
              <% @game_pieces.each_with_index do |game_piece| %>
                  <div class="col-lg-2 col-sm-2">
                    <label for=<%= 'opponent_category_id_' + game_piece.id.to_s %>>
                      <% if @eligible_game_pieces.include?(game_piece.id) %>
                          <div id=<%= game_piece.category_id %> data-add-border-challenge-opponent>
                            <%= radio_button_tag :opponent_category_id, game_piece.category_id, game_piece.category_id == @chosen_opponent_category_id, :style => 'display:none;' %>
                            <img class="image-icon" src=<%= image_path(game_piece.image_url) %> />
                            <span class="opponent-character selected-category-checkmark-challenge hidden">&#x2714;</span>
                          </div>
                      <% else %>
                          <img class="image-icon image-opaque" src=<%= image_path(game_piece.image_url) %>/>
                      <% end %>
                    </label>
                  </div>
              <% end %>
              <div class="clearfix"></div>
            </div>
            <hr/>
            <h2 class="text-center">Choose a Character to Wager</h2>
            <hr/>
            <div>
              <% @game_pieces.each_with_index do |game_piece| %>
                  <div class="col-lg-2 col-sm-2">
                    <label for=<%= 'wager_category_id_' + game_piece.id.to_s %>>
                      <% if @player_game_pieces.include?(game_piece.id) %>
                          <div id=<%= game_piece.category_id %> data-add-border-challenge-wager>
                            <%= radio_button_tag :wager_category_id, game_piece.category_id, game_piece.category_id == @chosen_wager_category_id, :style => 'display:none;' %>
                            <img class="image-icon" src=<%= image_path(game_piece.image_url) %> />
                            <span class="wager-character selected-category-checkmark-challenge hidden">&#x2714;</span>
                          </div>
                      <% else %>
                          <img class="image-icon image-opaque" src=<%= image_path(game_piece.image_url) %>/>
                      <% end %>
                    </label>
                  </div>
              <% end %>
              <div class="clearfix"></div>
            </div>
          </div>
      <hr/>
      <div class="col-lg-offset-2 col-sm-offset-2 disabled">
        <%= submit_tag 'Play', :class => 'btn btn-lg btn-success col-lg-10 col-sm-10 disabled', :id => 'choose-category-submit' %>
        <div class="clearfix"></div>
      </div>
  <% end %>
</div>
<hr/>

app/views/gameplay/choose_category.html.erb
<div class="text-center">
<h2>Choose the Character You Want</h2>
</div>
<hr/>
<div class="media-body">
<%= form_tag(question_path, method: :get, multipart: true) do %>
    <%= hidden_field_tag :game_id, @game.id %>
      <!--TODO: set based on from path-->
      <%= hidden_field_tag :is_crown, true %>
      <%= hidden_field_tag :is_challenge, false %>
    <% @game_pieces_in_threes.each_with_index do |game_piece_array| %>
        <div class="row">
          <div class="col-lg-offset-3 col-sm-offset-1">
            <% game_piece_array.each_with_index do |game_piece| %>
            <div class="col-lg-3 col-sm-4">
              <label for=<%= 'category_id_' + game_piece.id.to_s %>>
                <% if @player_game_pieces.include?(game_piece.id) %>
                    <img class="image-icon image-opaque" src=<%= image_path(game_piece.image_url) %>/>
                <% else %>
                    <div id=<%= game_piece.category_id %> data-add-border>
                      <%= radio_button_tag :category_id, game_piece.category_id, game_piece.category_id == @chosen_category, :style => 'display:none;' %>
                      <%= image_tag( game_piece.image_url) %>
                      <span class="selected-category-checkmark hidden">&#x2714;</span>
                    </div>
                <% end %>
              </label>
            </div>
            <% end %>
            <div class="clearfix"></div>
          </div>
          <br/>
        </div>
    <% end %>
          <hr/>
          <div class="col-lg-offset-2 col-sm-offset-2 disabled">
            <%= submit_tag 'Play', :class => 'btn btn-lg btn-success col-lg-10 col-sm-10 disabled', :id => 'choose-category-submit' %>
            <div class="clearfix"></div>
          </div>
  <% end %>
</div>
<hr/>

app/views/gameplay/spin.js.erb
document.getElementById('spinning_wheel_audio').play();
setTimeout(function(){
    $('#spinner_image').rotate({
        animateTo: <%= @rotation.to_i %>,
        duration: 6200,
        callback: function(){
            if(<%= @random_category_id == -1 %>){
                $('#crown_modal').attr('data_keyboard', 'false');
                $('#crown_modal').attr('data-backdrop', 'static');
                $('#crown_dismiss_button').addClass('hidden');
                $('#crown_modal').modal('show');
            } else{
                $('#play_modal_div').append("<%= j render 'gameplay/modals/play_modal' %>");
                $("#play_category_header").text('<%= @category_string.to_s.capitalize %>');
                $("#play_category_image").attr('src', '<%= image_url(@category_image_url) %>');
                $('#play_modal').modal('show');
            }
        }
    });
}, 500);

app/views/gameplay/spinner.html.erb
<div class="media">
  <div class="media-body">
      <div class="row col-lg-12 col-sm-12 media-heading">
        <h4 class="row col-lg-12 col-sm-12 text-center">Round <%= @game.round %></h4>
        <div class="clearfix"></div>
        <hr/>
      </div>
      <div class="row col-lg-12 col-sm-12">
        <div class="col-lg-6 col-sm-6 text-center divider-right">
          <div class="row">
              <div class="col-lg-6 col-sm-6">
                <% if current_user.image.nil? == false %>
                    <% if current_user.provider == 'facebook' %>
                        <img class="image-icon-small" src=<%= current_user.image + '?width=100&height=100' %>>
                    <% else %>
                        <img class="image-icon-small" src=<%= current_user.image %>>
                    <% end %>
                <% else %>
                    <img class="image-icon-small" src=<%= image_path('default-player-icon.png') %>>
                <% end %>
              </div>
              <div class="col-lg-3 col-sm-3">
                <% if current_user.username.nil? == false %>
                    <h5><%= current_user.username %></h5>
                <% else %>
                    <h5><%= current_user.email %></h5>
                <% end %>
              </div>
              <div class="clearfix"></div>
          </div>
          <br/>
          <div class="row col-lg-12 col-sm-12">
                <% @game_pieces.each do |game_piece| %>
                <div class="col-lg-2 col-sm-3" >
                  <% if @player_game_pieces.include?(game_piece.id) %>
                      <img class="image-icon" src=<%= image_path(game_piece.image_url) %>/>
                  <% else %>
                      <img class="image-icon image-opaque" src=<%= image_path(game_piece.image_url) %>/>
                  <% end %>
                </div>
            <% end %>
            <div class="clearfix"></div>
          </div>
          <br/>
        </div>
        <div class="col-lg-6 col-sm-6 text-center divider-left">
          <div class="row">
            <div class="col-lg-6 col-sm-6">
              <% if @opponent.image.nil? == false %>
                  <% if @opponent.provider == 'facebook' %>
                      <img class="image-icon-small" src=<%= @opponent.image + '?width=150&height=150' %>>
                  <% else %>
                      <img class="image-icon-small" src=<%= @opponent.image %>>
                  <% end %>
              <% else %>
                  <img class="image-icon-small" src=<%= image_path('default-player-icon.png') %>>
              <% end %>
            </div>
            <div class="col-lg-3 col-sm-3">
              <% if @opponent.username.nil? == false %>
                <h5><%= @opponent.username %></h5>
              <% else %>
                  <h5><%= @opponent.email %></h5>
              <% end %>
            </div>
          </div>
          <br/>
          <div class="row col-lg-12 col-sm-12">
            <% @game_pieces.each do |game_piece| %>
                <div class="col-lg-2 col-sm-3" >
                  <% if @opponent_game_pieces.include?(game_piece.id) %>
                    <img class="image-icon" src=<%= image_path(game_piece.image_url) %>/>
                  <% else %>
                    <img class="image-icon image-opaque" src=<%= image_path(game_piece.image_url) %>/>
                  <% end %>
                </div>
            <% end %>
          </div>
          <br/>
        </div>
        <div class="clearfix"></div>
      </div>
    <div class="clearfix"></div>
    <hr/>
    <div class="col-lg-12 col-sm-12">
      <div class="col-lg-offset-3 col-sm-offset-3">
            <img id='spinner_image' style='z-index: 1000;' class="row col-lg-8 col-sm-8" src=<%= image_path('Gameplay/SpinnerCropped.gif') %>>
        <%= link_to  gameplay_spin_path(@game.id), remote: true do %>
            <img id='spinner_button' class="spinner-button" src=<%= image_path('Gameplay/SpinButton.gif') %>>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
    <div class="clearfix"></div>
    <hr/>
    <div class="row">
      <div class="col-lg-12 col-sm-12">
        <div class="col-lg-offset-2 col-sm-offset-1 row">
            <% [1,2,3].each do |crown_ind| %>
                <% if @player_game_detail.correct_answers >= crown_ind %>
                    <div class="col-lg-2 col-sm-2 crown-ind-box full"></div>
                <% else%>
                  <div class="col-lg-2 col-sm-2 crown-ind-box empty"></div>
                <% end %>
            <% end %>
        </div>
      </div>
    </div>
    <br>
      <div class="row col-lg-12 col-sm-12">
        <div class="col-lg-offset-3 col-sm-offset-3">
          <% if @player_game_detail.correct_answers >= 3 %>
              <%= link_to 'Crown', '#',
                      class: 'btn btn-lg btn-primary col-lg-8 col-sm-8',
                      'data-target' => '#crown_modal',
                      'data-toggle' => 'modal'  %>
          <% else %>
              <button type="button" class='btn btn-lg btn-primary col-lg-8 col-sm-8 disabled'>Crown</button>
          <% end %>
        </div>
        <div class="clearfix"></div>
        <hr/>
      </div>
    <hr/>
    <%= render 'gameplay/modals/crown_modal' %>
  </div>
  <%= audio_tag('spinning_wheel.mp3', controls: true, id:'spinning_wheel_audio', class: 'hidden') %>
</div>

<div id="play_modal_div"></div>
<%= render 'gameplay/modals/message_modal' %>
<% if (@player_game_detail.shown_crown_message? == false && @player_game_detail.correct_answers >= 3) %>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#message_modal').modal('show');
        });
    </script>
<% end %>