config/routes.rb
Rails.application.routes.draw do

  get 'admin/admin'

  get 'submit_question/create'

  resources :game_setups

  #admin routes
  get 'admin/admin/:page_number(/:keyword)', to:'admin#admin', as:'admin'
  get 'admin/edit_user/:id', to:'admin#edit_user', as:'admin_edit_user'
  post 'admin/update_user/:id', to:'admin#update_user', as:'admin_update_user'

  #gameplay routes
  get 'gameplay/spinner/:id', to: 'gameplay#spinner', as: 'gameplay_spinner'
  get 'gameplay/spin/:game_id', to: 'gameplay#spin', as: 'gameplay_spin'
  get 'gameplay/choose_category/:game_id', to: 'gameplay#choose_category', as:'gameplay_choose_category'
  get 'gameplay/challenge_select_pieces/:game_id', to: 'gameplay#challenge_select_pieces', as: 'challenge_select_pieces'
  get 'gameplay/challenge_setup', to: 'gameplay#challenge_setup', as: 'challenge_setup'
  get 'gameplay/challenge_next_question/:game_id/:challenge_id', to: 'gameplay#challenge_next_question', as: 'challenge_next_question'

  #question routes
  get 'question/question/:game_id/:category_id/:is_crown/:is_challenge(/:challenge_id)', to: 'question#question', as: 'question_with_params'
  get 'question/question', to: 'question#question', as: 'question'
  get 'question/answered_question/:game_id/:question_id/:answer_id/:is_crown/:is_challenge(/:challenge_id)(/:did_not_answer)', to: 'question#answered_question', as: 'answered_question'

  get 'powerup/fifty_fifty/:is_crown_or_challenge', to: 'powerup#fifty_fifty', as: 'power_up_fifty_fifty'
  get 'powerup/extend_time/:is_crown_or_challenge', to: 'powerup#extend_time', as: 'power_up_extend_time'
  get 'powerup/skip_question/:game_id/:question_id/:answer_id/:is_crown/:is_challenge(/:challenge_id)', to: 'powerup#skip_question', as: 'power_up_skip_question'

  #question_ratings routes
  get 'question_rating/show/:question_id', to: 'question_rating#show', as: 'show_question_rating'
  post 'question_rating/create', to: 'question_rating#create', as: 'question_ratings'

  #opponent search routes
  get 'search_for_opponents/select_opponent/:page_number(/:keyword)', to: 'search_for_opponents#select_opponent', as: 'select_opponent'
  get 'search_for_opponents/create_game', to: 'search_for_opponents#create_game', as: 'create_game_with_opponent'

  #home routes
  get 'home/index'
  post 'home/create_game_setup', to: 'home#create_game_setup', as: 'create_game_setup'
  get 'home/setup_new_game/:id', to: 'home#setup_new_game', as: 'setup_new_game'

  #profile routes
  get 'profile/view'

  #submit question routes
  get 'submit_question/new', to: 'submit_question#new', as: 'submit_question'
  post 'submit_question/create', to: 'submit_question#create', as: 'create_question'

  #review questions routes
  get 'question_review/review(/:page_number)', to: 'question_review#review', as: 'review_questions'
  get 'question_review/approve/:question_id/:page_number', to: 'question_review#approve', as: 'approve_question'
  get 'question_review/deny/:question_id/:page_number', to: 'question_review#deny', as: 'deny_question'

  #devise routes
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  get 'welcome/index'

  root to: 'welcome#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :answers
  has_many :game_details, :through => :game_detail_questions
end

app/controllers/question_controller.rb
  class QuestionController < ApplicationController

  respond_to :html, :js

  include ApplicationHelper

  def question
    if(current_user && current_user.role == GlobalConstants::PLAYER)
      game_piece = GamePiece.where(category_id: params[:category_id]).first;
      @game_piece_image_url = game_piece.nil? == false ? game_piece.image_url : '';

      @is_crown = params[:is_crown]
      @is_challenge = params[:is_challenge]
      if(@is_challenge == :true.to_s)
        @challenge = GameChallenge.where(id: params[:challenge_id]).first
      end
      @game = Game.where(id: params[:game_id]).first
      @game_detail = @game.game_details.where(player_id: current_user.id).first
      if(@game_detail.correct_answers > 3 || @is_crown == 'true')
        @game_detail.shown_crown_message= true
        @game_detail.save
      end
      @category = Category.where(id: params[:category_id]).first
      @questions_asked_ids = GameDetailQuestion.where(game_detail_id: @game_detail.id).uniq.pluck(:question_id)

      # TODO: remove && false once more questions are seeded into db
      if(@questions_asked_ids.count > 0)
        @questions = Question.where('category_id = ? AND active = ? AND id NOT IN (?)', @category.id, true, @questions_asked_ids)
      else
        @questions = Question.where('category_id = ? AND active = ?', @category.id, true)
      end
      if(@questions.count < 1)
        flash[:error] = 'Oh no! I guess we need to add more questions to the pool.'
        redirect_to home_index_path
      else
        if(@is_crown == 'true')
          @game_detail.correct_answers = 0;
          @game_detail.save
        end
        @question = @questions.offset(rand(@questions.count)).first
        @answers = @question.answers.shuffle
        @correct_answer = @question.answers.where(is_correct: true).first
        GameDetailQuestion.create(game_detail_id: @game_detail.id, question_id: @question.id, question_answered: false)
      end
    else
      redirect_to welcome_index_path
    end

  end

  def answered_question
    if(current_user && current_user.role == GlobalConstants::PLAYER)
      @is_crown = params[:is_crown]
      @is_challenge = params[:is_challenge]
      @did_not_answer = params[:did_not_answer] == 'true' || false
      @power_up_skip = params[:power_up_skip] == 'true' || false

      puts 'did_not_answer: '
      puts @did_not_answer

      if(@is_challenge == :true.to_s)
        @challenge = GameChallenge.where(id: params[:challenge_id]).first
      else
        @challenge = nil
      end

      @game = Game.where(id: params[:game_id]).first
      @game_detail = @game.game_details.where(player_id: current_user.id).first
      @chosen_answer = Answer.where(id: params[:answer_id]).first

      @question = Question.where(id: params[:question_id]).first
      @answered_correctly = @did_not_answer == true ? false : @chosen_answer.is_correct
      @category = Category.where(id: @question.category_id).first

      @game_detail_question = GameDetailQuestion.where('game_detail_id= ? AND question_id= ?', @game_detail.id, @question.id).first

      # TODO: remove true once more questions are entered
      if(@game_detail_question.question_answered == false)
        @game_detail_question.question_answered= true
        @game_detail_question.save
        if(@power_up_skip == false)
          update_game_details(@game, @game_detail, @chosen_answer, @category, @is_crown, @is_challenge, @challenge, @did_not_answer)
        end
      else
        @player_tried_to_re_answer = true
      end
    else
      redirect_to welcome_index_path
    end
  end

  private

  def update_game_details(game, game_detail, answer, category, is_crown, is_challenge, challenge, did_not_answer)
    @answered_question = AnsweredQuestion.where('game_detail_id= ? AND category_id= ?', game_detail.id, category.id).first
    if(did_not_answer == false && answer.is_correct == true)
      if(is_crown == :true.to_s)
        handle_correct_crown(game, game_detail, category)
      elsif(is_challenge == :true.to_s)
        handle_correct_challenge(game_detail, challenge)
      else
        handle_correct_answer(game_detail)
      end
      game_detail.save
      if(@answered_question.nil? == true)
        AnsweredQuestion.create(game_detail_id: game_detail.id, category_id: category.id, correct_count: 1)
      else
        @answered_question.correct_count= @answered_question.correct_count + 1
        @answered_question.save
      end
    else
      if(@answered_question.nil? == true)
        AnsweredQuestion.create(game_detail_id: game_detail.id, category_id: category.id, incorrect_count: 1)
      else
        @answered_question.incorrect_count= @answered_question.incorrect_count + 1
        @answered_question.save
      end
      if(is_challenge == :true.to_s)
        handle_incorrect_challenge(game_detail, challenge)
      else
        handle_incorrect_answer(game, game_detail)
      end
    end
  end

  private

  def handle_correct_crown(game, game_detail, category)
    game_detail.correct_answers= 0
    game_detail.shown_crown_message = false
    @game_piece = GamePiece.where(category_id: category.id).first
    @player_game_pieces = GameDetailGamePiece.where(game_detail_id: @game_detail.id).pluck(:game_piece_id)
    if(@game_piece.nil? == false && @player_game_pieces.include?(@game_piece.id) == false)
      GameDetailGamePiece.create(game_detail_id: game_detail.id, game_piece_id: @game_piece.id)
    end
    total_game_pieces = GamePiece.all
    if(GameDetailGamePiece.where(game_detail_id: @game_detail.id).count == total_game_pieces.count)
      game.finished= true
      game.save
    end
    current_user.xp += GlobalConstants::CROWN_XP_VALUE
    handle_player_leveling
    current_user.currency += GlobalConstants::CROWN_CURRENCY_VALUE
    current_user.save
  end

  def handle_correct_challenge(game_detail, challenge)
    game_detail.correct_answers = 0
    game_detail.save
    if(current_user.id == challenge.player_id)
      challenge.player_correct_count = challenge.player_correct_count + 1
    elsif(current_user.id == challenge.opponent_id)
      challenge.opponent_correct_count = challenge.opponent_correct_count + 1
    end
    challenge.save
  end

  def handle_incorrect_challenge(game_detail, challenge)
    game_detail.correct_answers = 0
    game_detail.save
    if(current_user.id == challenge.player_id)
      challenge.player_incorrect_count = challenge.player_incorrect_count + 1
    elsif(current_user.id == challenge.opponent_id)
      challenge.opponent_incorrect_count = challenge.opponent_incorrect_count + 1
    end
    challenge.save
  end

  def handle_correct_answer(game_detail)
    game_detail.correct_answers= game_detail.correct_answers + 1
    if(game_detail.correct_answers > 3)
      game_detail.shown_crown_message = true
    end
    current_user.xp += GlobalConstants::REGULAR_QUESTION_XP_VALUE
    handle_player_leveling
    current_user.currency += GlobalConstants::REGULAR_QUESTION_CURRENCY_VALUE
    current_user.save
  end

  def handle_incorrect_answer(game, game_detail)
    game_detail.correct_answers = 0
    game_detail.save
    if(game.player_turn == game.player2_id)
      game.round= game.round + 1
    end
    game.player_turn = get_opponent(game).id
    game.save
  end

end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/question/modals/_answer_result_modal.erb
<div class="modal fade"
     id="answer_result_modal"
     tabindex="-1"
     role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true"
     data-backdrop="static"
     data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <% if @power_up_skip == true %>
            <h3 class="text-center">Question Skipped</h3>
        <% elsif @did_not_answer == true %>
            <h3 class="text-center">Time's Up!</h3>
        <% elsif @game.finished? == true || (@chosen_answer != nil && @chosen_answer.is_correct) %>
            <h3 class="text-center">Congratulations!</h3>
        <% elsif @player_tried_to_re_answer %>
            <h3 class="text-center">Trying to re-answer, eh?</h3>
        <% else %>
            <h3 class="text-center">Ooooh, too bad!</h3>
        <% end %>

      </div>
      <div class="modal-body">
        <div class="col-lg-12 col-sm-12">
          <% if @power_up_skip %>
              <h4 class="text-center">Good thing you had those coins!</h4>
          <% elsif @game.finished? == true %>
              <h4 class="text-center">You Won the Game!</h4>
          <% elsif @player_tried_to_re_answer %>
            <h4 class="text-center">No Can Do!</h4>
          <% elsif @did_not_answer == true %>
              <h4 class="text-center">So sorry!</h4>
          <% elsif (@chosen_answer != nil && @chosen_answer.is_correct) %>
            <h4 class="text-center">You answered correctly!</h4>
          <% else %>
              <h4 class="text-center">That answer just wasn't good enough!</h4>
          <% end %>

          <br/>
          <div class="text-center" id="rate-question-button-div">
            <%= link_to 'Rate this Question', show_question_rating_path(@question.id), class: 'btn btn-primary', id: 'rate-question-button', remote: true %>
          </div>
          <div id="question-rating-form" style="display:none;"></div>
          <div id="thank-you-message" style="display:none;"></div>
          <br/>

          <div class="text-center">
            <% if @is_challenge == :true.to_s %>
                <%= link_to 'Next Question', challenge_next_question_path(@game.id, @challenge.id), class:'btn btn-success' %>
            <% elsif (@chosen_answer != nil && @chosen_answer.is_correct? == true) || @power_up_skip == true %>
                <%= link_to 'Back to Game', gameplay_spinner_path(@game), class:'btn btn-success' %>
            <% else %>
                <%= link_to 'Home', home_index_path, class:'btn btn-success' %>
            <% end %>
          </div>
        </div>
        <div class="clearfix"></div>
        <br/>
      </div>
    </div>
  </div>
</div>